config/routes.rb
Rails.application.routes.draw do
  get 'sign_up' =>'users#new',as:'sign_up'
  root 'joblists#index'
  resources :users
  resources :joblists
  resources :sessions
  resources :userdats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/joblist.rb
class Joblist < ApplicationRecord
	validates :title,presence: true,length:{ minimum:5 }
	validates :description,presence:true,length:{ minimum:10 }
	validates :status,presence:true
end

app/models/user.rb
class User < ApplicationRecord
	include Humanizer 
	require_human_on :create

	validates :username,presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, uniqueness: true,on: :create,length:{minimum:5},confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	helper_method :current_user,:check_current_user

	def current_user
		current_user ||= User.where("id = ?",session[:user]).first
	end

	def check_current_user
		if current_user.blank?
			flash[:error] = "please login first before run teh action"
			redirect_to new_session_url
		else
			current_user
		end
	end
end

app/controllers/joblists_controller.rb
class JoblistsController < ApplicationController
  before_action :check_current_user, only:[:new,:edit,:update,:create,:destroy]

  def index
  	@joblists = Joblist.all
  end

  def new
  	@joblist = Joblist.new
  end

  def edit
    @joblist = Joblist.find_by_id(params[:id])
  end

  def show
    @joblist = Joblist.find_by_id(params[:id])
  end

  def destroy
    @joblist = Joblist.find_by_id(params[:id])
    if @joblist.destroy
      flash[:notice] = "Success"
      redirect_to action:'index'
    else
      flash[:errors] = "fails"
      redirect_to action:'index'
    end
  end

  def update
    @joblist = Joblist.find_by_id(params[:id])
    if @joblist.update(params_joblist)
      flash[:notice] = "Success"
      redirect_to action:'index'
    else
      flash[:errors] = "data not valid"
      render 'edit'
    end
  end

  def create 
  	@joblist = Joblist.new(params_joblist)
  	if @joblist.save
  	  flash[:notice] = "add new job to fucking normies"
  	  redirect_to action:'index'
  	else 
  	  flash[:errors] = "fails bro"
  	  render 'new'
  	end
  end

  private
  def params_joblist
  	params.require(:joblist).permit(:title,:description,:status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		username = params[:username]
		password = params[:password]
		user = User.where("username  = ? ",username).first
		user_password = User.where("password = ? ",password).first
		if !user_password.blank? 
			session[:user] = user.id
			flash[:notice] = "Welcome #{user.username}"
			redirect_to root_url
		else
			params[:username]
			flash[:error] = "your data not valid"
			render 'new'
		end
	end

	def destroy
		session[:user] = nil
		flash[:notice] = "logout session success"
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  	@user = User.new
  end

  def edit

  end

  def create
  	@user = User.new(params_user)
  	if @user.save
  		flash[:notice] = "success"
  		redirect_to root_url
 	else
 		flash[:error] = "fails"
 		render 'new'
  	end
  end

  private
  def params_user
  	params.require(:user).permit(:username,:email,:password,:password_confirmation,:humanizer_answer,:humanizer_question_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/joblists/edit.html.erb
<div class="jumbotron jumbotron-fluid">
  	<div class="container container" style="align-self: center;">
		<%= form_for @joblist do |f| %>
		<%= f.label :title %>
		<br/>
		<%= f.text_field :title %>
		<br/>
		<%= f.label :description %>
		<br/>
		<%= f.text_field :description%>
		<br/>
		<br/>
		<%= f.label :status%>
		<br/>
		<%= f.radio_button :status,'available' %>
		<%= label :joblist_status,'available'%>
		<%= f.radio_button :status,'unavailable'%>
		<%= label :joblist_status,'unavailable'%>
		<br/>
		<%= f.submit :update,class:"btn btn-warning",style:"color:white"%>
		<%= link_to 'kembali',joblists_path,class:"btn"%>
		<%end%>
	</div>
</div>

app/views/joblists/index.html.erb
<!-- head job -->
<div class="jumbotron jumbotron-fluid" style="background-color: #018383;color: white">
  	<div class="container">
	  <h1>Anda kurang kerjaan?</h1>
	  <p>Kami hadir untuk menemani dan mencarikan kegabutan anda</p>
  	  <h4>
		<% if !current_user %>
			<%= link_to 'log in', new_session_path,class:'btn btn-warning',style:"color:white" %>
			<%= link_to 'sign up',sign_up_path,class:'btn btn-warning',style:"color:white"%>
		<% else %> 
			<%= link_to 'log out', session_path(current_user.id), method:"DELETE",class:"btn btn-warning",style:"color:white"%>
			<%= link_to 'new job',new_joblist_path,class:'btn btn-warning',style:"color:white"%>
		<% end %>
	  </h4>
	</div>
</div>

<!-- list job -->
<div class="card-columns" style="padding-right: 20px;padding-left: 20px;font-family: Trebuchet;">
	<% @joblists.each do |job|%>
		<div class="card bg-light"  style="color:#02a8a8;tex">
		    <div class="card-body text-center" style="background-color: #f5dea3">
				<h2><strong><%= job.title %></strong></h2>
				<div class="btn-group">
				<% if !current_user %>
					<%= link_to 'readmore',joblist_path(job.id),class:'btn btn-info'%>
				<% elsif current_user.username  == 'Admin' %>
					<%= link_to 'readmore',joblist_path(job.id),class:'btn btn-info'%>
					<%= link_to 'edit',edit_joblist_path(job.id),class:'btn btn-secondary'%>
					<%= link_to 'delete',joblist_path(job.id),method:'delete',data:{confirm:"delete this fucking job?"},class:'btn btn-secondary'%>
				<% else %>
					<%= link_to 'readmore',joblist_path(job.id),class:'btn btn-info'%>
				<% end %>
				</div>
				<hr/>
				<% if job.status == 'available'%>
					<i style="color:green">status : <%= job.status %></i></p>
				<% else %>
					<i style="color:red">status : <%= job.status %></i></p>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/joblists/new.html.erb
<div class="jumbotron jumbotron-fluid">
  	<div class="container container" style="align-self: center;">
		<%= form_for @joblist do |f|%>
			<%= f.label :title %>
			<br/>
			<%= f.text_field :title %>
			<%= @joblist.errors[:title].first unless @joblist.errors[:title].blank? %>
			<br/>
			<%= 
			f.label :description %>
			<br/>
			<%= f.text_field :description%>
			<%= @joblist.errors[:description].first unless @joblist.errors[:description].blank?%>
			<br/>
			<%= f.label :status %>
			<br/>
			<%= f.radio_button :status,'available',:checked =>true%>
			<%= label :joblist_status,'available'%>
			<%= f.radio_button :status,'unavailable'%>
			<%= label :joblist_status,'unavailable'%>
			<br/>
			<%= f.submit :submit,class:"btn btn-info" %>
			<%= link_to 'kembali ',joblists_path,class:"btn"%>
		<% end %>
	</div>
</div>

app/views/joblists/show.html.erb
<div class="jumbotron jumbotron-fluid" style="background-color: #f5dea3;color: #02a8a8">
  	<div class="container">
		<h3><%= @joblist.title %></h3>
		<p><i><%= @joblist.description %></i></p>
		<p><%= link_to 'back to index', joblists_path, class:'btn btn-info'%></p>
		<% if @joblist.status == 'available'%>
			<i style="color:green">status : <%= @joblist.status %></i></p>
		<% else %>
			<i style="color:red">status : <%= @joblist.status %></i></p>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #02a8a8">
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="jumbotron jumbotron-fluid">
  	<div class="container container text-center">
		<%= form_for @user do |f|%>
			<%= f.label :username %>
			<br/>
			<%= f.text_field :username %>
			<%= @user.errors[:username].first unless @user.errors[:username].blank? %>
			<br/>
			<%= f.label :email %>
			<br/>
			<%= f.text_field :email %>
			<%= @user.errors[:email].first unless @user.errors[:email].blank? %>
			<br/>
			<%= f.label :password %>
			<br/>
			<%= f.password_field :password %>
			<%= @user.errors[:password].first unless @user.errors[:password].blank?%>
			<br/>
			<%= f.label :password_confirmation %>
			<br/>
			<%= f.password_field :password_confirmation%>
			<%= @user.errors[:password_confirmation].first unless @user.errors[:password_confirmation].blank?%>
			<br/>
			<%= f.label :humanizer_answer,@user.humanizer_question %>
			<br/>
			<%= f.text_field :humanizer_answer %>
			<%= f.hidden_field :humanizer_question_id%>
			<br/>
			<br/>
			<%= f.submit :submit,class:"btn btn-warning",style:"color:white"%>
			<%= link_to 'kembali',joblists_path,class:"btn btn-warning",style:"color:white"%>
		<% end %>
	</div>
</div>